--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create layer_room_top
local layer_room_top=cc.Node:create()
layer_room_top:setName("layer_room_top")
layout = ccui.LayoutComponent:bindLayoutComponent(layer_room_top)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create img_menu_bg
local img_menu_bg = ccui.ImageView:create()
img_menu_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/menu.plist")
img_menu_bg:loadTexture("menu_bg.png",1)
img_menu_bg:setLayoutComponentEnabled(true)
img_menu_bg:setName("img_menu_bg")
img_menu_bg:setTag(126)
img_menu_bg:setCascadeColorEnabled(true)
img_menu_bg:setCascadeOpacityEnabled(true)
img_menu_bg:setAnchorPoint(0.5000, 1.0000)
img_menu_bg:setPosition(1830.2740, 1009.0000)
img_menu_bg:setScaleY(0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(img_menu_bg)
layout:setPositionPercentX(0.9533)
layout:setPositionPercentY(0.9343)
layout:setPercentWidth(0.0625)
layout:setPercentHeight(0.5102)
layout:setSize({width = 120.0000, height = 551.0000})
layout:setLeftMargin(1770.2740)
layout:setRightMargin(29.7257)
layout:setTopMargin(71.0000)
layout:setBottomMargin(458.0000)
layer_room_top:addChild(img_menu_bg)

--Create img_menu_item1
local img_menu_item1 = ccui.ImageView:create()
img_menu_item1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/menu.plist")
img_menu_item1:loadTexture("i_menu_item_setting.png",1)
img_menu_item1:setLayoutComponentEnabled(true)
img_menu_item1:setName("img_menu_item1")
img_menu_item1:setTag(127)
img_menu_item1:setCascadeColorEnabled(true)
img_menu_item1:setCascadeOpacityEnabled(true)
img_menu_item1:setPosition(59.0000, 365.5490)
layout = ccui.LayoutComponent:bindLayoutComponent(img_menu_item1)
layout:setPositionPercentX(0.4917)
layout:setPositionPercentY(0.6634)
layout:setPercentWidth(0.5833)
layout:setPercentHeight(0.1960)
layout:setSize({width = 70.0000, height = 108.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(26.0000)
layout:setTopMargin(131.4510)
layout:setBottomMargin(311.5490)
img_menu_bg:addChild(img_menu_item1)

--Create img_menu_item2
local img_menu_item2 = ccui.ImageView:create()
img_menu_item2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/menu.plist")
img_menu_item2:loadTexture("i_menu_item_dissolve.png",1)
img_menu_item2:setLayoutComponentEnabled(true)
img_menu_item2:setName("img_menu_item2")
img_menu_item2:setTag(128)
img_menu_item2:setCascadeColorEnabled(true)
img_menu_item2:setCascadeOpacityEnabled(true)
img_menu_item2:setPosition(59.0000, 222.4500)
layout = ccui.LayoutComponent:bindLayoutComponent(img_menu_item2)
layout:setPositionPercentX(0.4917)
layout:setPositionPercentY(0.4037)
layout:setPercentWidth(0.5833)
layout:setPercentHeight(0.1960)
layout:setSize({width = 70.0000, height = 108.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(26.0000)
layout:setTopMargin(274.5500)
layout:setBottomMargin(168.4500)
img_menu_bg:addChild(img_menu_item2)

--Create img_menu_item3
local img_menu_item3 = ccui.ImageView:create()
img_menu_item3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/menu.plist")
img_menu_item3:loadTexture("i_menu_item_exit.png",1)
img_menu_item3:setLayoutComponentEnabled(true)
img_menu_item3:setName("img_menu_item3")
img_menu_item3:setTag(129)
img_menu_item3:setCascadeColorEnabled(true)
img_menu_item3:setCascadeOpacityEnabled(true)
img_menu_item3:setPosition(59.0000, 83.6800)
layout = ccui.LayoutComponent:bindLayoutComponent(img_menu_item3)
layout:setPositionPercentX(0.4917)
layout:setPositionPercentY(0.1519)
layout:setPercentWidth(0.5833)
layout:setPercentHeight(0.1960)
layout:setSize({width = 70.0000, height = 108.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(26.0000)
layout:setTopMargin(413.3200)
layout:setBottomMargin(29.6800)
img_menu_bg:addChild(img_menu_item3)

--Create img_menu
local img_menu = ccui.ImageView:create()
img_menu:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/menu.plist")
img_menu:loadTexture("i_menu_pull_down.png",1)
img_menu:setLayoutComponentEnabled(true)
img_menu:setName("img_menu")
img_menu:setTag(125)
img_menu:setCascadeColorEnabled(true)
img_menu:setCascadeOpacityEnabled(true)
img_menu:setPosition(1828.0000, 990.7833)
layout = ccui.LayoutComponent:bindLayoutComponent(img_menu)
layout:setPositionPercentX(0.9521)
layout:setPositionPercentY(0.9174)
layout:setPercentWidth(0.0609)
layout:setPercentHeight(0.1102)
layout:setSize({width = 117.0000, height = 119.0000})
layout:setLeftMargin(1769.5000)
layout:setRightMargin(33.5000)
layout:setTopMargin(29.7167)
layout:setBottomMargin(931.2833)
layer_room_top:addChild(img_menu)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(40)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(1830.2740)
localFrame:setY(1003.7250)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(1830.2740)
localFrame:setY(995.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(1830.2740)
localFrame:setY(1009.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(img_menu_bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(0.0001)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(0.0001)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(img_menu_bg)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(img_menu_bg)
--Create Animation List

result['root'] = layer_room_top
return result;
end

return Result

