--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create node_room_player_head
local node_room_player_head=cc.Node:create()
node_room_player_head:setName("node_room_player_head")

--Create node_head
local node_head=cc.Node:create()
node_head:setName("node_head")
node_head:setTag(31)
node_head:setCascadeColorEnabled(true)
node_head:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head)
node_room_player_head:addChild(node_head)

--Create img_circle
local img_circle = ccui.ImageView:create()
img_circle:ignoreContentAdaptWithSize(false)
img_circle:loadTexture("assets/common/i_head_circle.png",0)
img_circle:setLayoutComponentEnabled(true)
img_circle:setName("img_circle")
img_circle:setTag(129)
img_circle:setCascadeColorEnabled(true)
img_circle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_circle)
layout:setSize({width = 206.5000, height = 206.5000})
layout:setLeftMargin(-103.2500)
layout:setRightMargin(-103.2500)
layout:setTopMargin(-103.2500)
layout:setBottomMargin(-103.2500)
node_room_player_head:addChild(img_circle)

--Create img_ting
local img_ting = ccui.ImageView:create()
img_ting:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/table.plist")
img_ting:loadTexture("i_waiting_card.png",1)
img_ting:setLayoutComponentEnabled(true)
img_ting:setName("img_ting")
img_ting:setTag(26)
img_ting:setCascadeColorEnabled(true)
img_ting:setCascadeOpacityEnabled(true)
img_ting:setVisible(false)
img_ting:setPosition(75.0000, 66.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_ting)
layout:setSize({width = 85.0000, height = 101.0000})
layout:setLeftMargin(32.5000)
layout:setRightMargin(-117.5000)
layout:setTopMargin(-116.5000)
layout:setBottomMargin(15.5000)
node_room_player_head:addChild(img_ting)

--Create img_banker
local img_banker = ccui.ImageView:create()
img_banker:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/table.plist")
img_banker:loadTexture("i_banker.png",1)
img_banker:setLayoutComponentEnabled(true)
img_banker:setName("img_banker")
img_banker:setTag(27)
img_banker:setCascadeColorEnabled(true)
img_banker:setCascadeOpacityEnabled(true)
img_banker:setVisible(false)
img_banker:setPosition(-75.0000, 66.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_banker)
layout:setSize({width = 49.0000, height = 53.0000})
layout:setLeftMargin(-99.5000)
layout:setRightMargin(50.5000)
layout:setTopMargin(-92.5000)
layout:setBottomMargin(39.5000)
node_room_player_head:addChild(img_banker)

--Create txt_name
local txt_name = ccui.Text:create()
txt_name:ignoreContentAdaptWithSize(true)
txt_name:setTextAreaSize({width = 0, height = 0})
txt_name:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_name:setFontSize(32)
txt_name:setString([[西边小姐姐]])
txt_name:setLayoutComponentEnabled(true)
txt_name:setName("txt_name")
txt_name:setTag(28)
txt_name:setCascadeColorEnabled(true)
txt_name:setCascadeOpacityEnabled(true)
txt_name:setPosition(0.0000, -66.6600)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_name)
layout:setSize({width = 162.0000, height = 39.0000})
layout:setLeftMargin(-81.0000)
layout:setRightMargin(-81.0000)
layout:setTopMargin(47.1600)
layout:setBottomMargin(-86.1600)
node_room_player_head:addChild(txt_name)

--Create img_gold
local img_gold = ccui.ImageView:create()
img_gold:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/table.plist")
img_gold:loadTexture("i_gold.png",1)
img_gold:setLayoutComponentEnabled(true)
img_gold:setName("img_gold")
img_gold:setTag(29)
img_gold:setCascadeColorEnabled(true)
img_gold:setCascadeOpacityEnabled(true)
img_gold:setPosition(-72.3774, -112.3995)
layout = ccui.LayoutComponent:bindLayoutComponent(img_gold)
layout:setSize({width = 34.0000, height = 31.0000})
layout:setLeftMargin(-89.3774)
layout:setRightMargin(55.3774)
layout:setTopMargin(96.8995)
layout:setBottomMargin(-127.8995)
node_room_player_head:addChild(img_gold)

--Create txt_gold
local txt_gold = ccui.Text:create()
txt_gold:ignoreContentAdaptWithSize(true)
txt_gold:setTextAreaSize({width = 0, height = 0})
txt_gold:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_gold:setFontSize(30)
txt_gold:setString([[3000]])
txt_gold:setLayoutComponentEnabled(true)
txt_gold:setName("txt_gold")
txt_gold:setTag(30)
txt_gold:setCascadeColorEnabled(true)
txt_gold:setCascadeOpacityEnabled(true)
txt_gold:setAnchorPoint(0.0000, 0.5000)
txt_gold:setPosition(-47.3570, -111.4518)
txt_gold:setTextColor({r = 239, g = 195, b = 18})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_gold)
layout:setSize({width = 89.0000, height = 37.0000})
layout:setLeftMargin(-47.3570)
layout:setRightMargin(-41.6430)
layout:setTopMargin(92.9518)
layout:setBottomMargin(-129.9518)
node_room_player_head:addChild(txt_gold)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = node_room_player_head
return result;
end

return Result

