--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create layer_room_player_head
local layer_room_player_head=cc.Node:create()
layer_room_player_head:setName("layer_room_player_head")
layout = ccui.LayoutComponent:bindLayoutComponent(layer_room_player_head)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create file_node_left_player_head
innerCSD = require("layouts.ui.room.room_player_head_node_layout")
innerProject = innerCSD.create(callBackProvider)
local file_node_left_player_head = innerProject.root
file_node_left_player_head.animation = innerProject.animation
file_node_left_player_head:setName("file_node_left_player_head")
file_node_left_player_head:setTag(76)
file_node_left_player_head:setCascadeColorEnabled(true)
file_node_left_player_head:setCascadeOpacityEnabled(true)
file_node_left_player_head:setPosition(105.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(file_node_left_player_head)
layout:setPositionPercentX(0.0547)
layout:setPositionPercentY(0.5926)
layout:setLeftMargin(105.0000)
layout:setRightMargin(1815.0000)
layout:setTopMargin(440.0000)
layout:setBottomMargin(640.0000)
innerProject.animation:setTimeSpeed(1.0000)
file_node_left_player_head:runAction(innerProject.animation)
layer_room_player_head:addChild(file_node_left_player_head)

--Create file_node_player_self_head
innerCSD = require("layouts.ui.room.room_player_head_node_layout")
innerProject = innerCSD.create(callBackProvider)
local file_node_player_self_head = innerProject.root
file_node_player_self_head.animation = innerProject.animation
file_node_player_self_head:setName("file_node_player_self_head")
file_node_player_self_head:setTag(98)
file_node_player_self_head:setCascadeColorEnabled(true)
file_node_player_self_head:setCascadeOpacityEnabled(true)
file_node_player_self_head:setPosition(105.0000, 300.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(file_node_player_self_head)
layout:setPositionPercentX(0.0547)
layout:setPositionPercentY(0.2778)
layout:setLeftMargin(105.0000)
layout:setRightMargin(1815.0000)
layout:setTopMargin(780.0000)
layout:setBottomMargin(300.0000)
innerProject.animation:setTimeSpeed(1.0000)
file_node_player_self_head:runAction(innerProject.animation)
layer_room_player_head:addChild(file_node_player_self_head)

--Create file_node_right_player_head
innerCSD = require("layouts.ui.room.room_player_head_node_layout")
innerProject = innerCSD.create(callBackProvider)
local file_node_right_player_head = innerProject.root
file_node_right_player_head.animation = innerProject.animation
file_node_right_player_head:setName("file_node_right_player_head")
file_node_right_player_head:setTag(106)
file_node_right_player_head:setCascadeColorEnabled(true)
file_node_right_player_head:setCascadeOpacityEnabled(true)
file_node_right_player_head:setPosition(1815.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(file_node_right_player_head)
layout:setPositionPercentX(0.9453)
layout:setPositionPercentY(0.5926)
layout:setLeftMargin(1815.0000)
layout:setRightMargin(105.0000)
layout:setTopMargin(440.0000)
layout:setBottomMargin(640.0000)
innerProject.animation:setTimeSpeed(1.0000)
file_node_right_player_head:runAction(innerProject.animation)
layer_room_player_head:addChild(file_node_right_player_head)

--Create file_node_opposite_player_head
innerCSD = require("layouts.ui.room.room_player_head_node_layout")
innerProject = innerCSD.create(callBackProvider)
local file_node_opposite_player_head = innerProject.root
file_node_opposite_player_head.animation = innerProject.animation
file_node_opposite_player_head:setName("file_node_opposite_player_head")
file_node_opposite_player_head:setTag(114)
file_node_opposite_player_head:setCascadeColorEnabled(true)
file_node_opposite_player_head:setCascadeOpacityEnabled(true)
file_node_opposite_player_head:setPosition(1570.0000, 980.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(file_node_opposite_player_head)
layout:setPositionPercentX(0.8177)
layout:setPositionPercentY(0.9074)
layout:setLeftMargin(1570.0000)
layout:setRightMargin(350.0000)
layout:setTopMargin(100.0000)
layout:setBottomMargin(980.0000)
innerProject.animation:setTimeSpeed(1.0000)
file_node_opposite_player_head:runAction(innerProject.animation)
layer_room_player_head:addChild(file_node_opposite_player_head)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = layer_room_player_head
return result;
end

return Result

