--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create setting_layer
local setting_layer=cc.Node:create()
setting_layer:setName("setting_layer")
layout = ccui.LayoutComponent:bindLayoutComponent(setting_layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/common/popup_bg1.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(72)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(960.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4167)
layout:setPercentHeight(0.4630)
layout:setSize({width = 800.0000, height = 500.0000})
layout:setLeftMargin(560.0000)
layout:setRightMargin(560.0000)
layout:setTopMargin(290.0000)
layout:setBottomMargin(290.0000)
setting_layer:addChild(img_bg)

--Create img_title_bg
local img_title_bg = ccui.ImageView:create()
img_title_bg:ignoreContentAdaptWithSize(false)
img_title_bg:loadTexture("assets/common/title_bg1.png",0)
img_title_bg:setScale9Enabled(true)
img_title_bg:setCapInsets({x = 21, y = 21, width = 758, height = 79})
img_title_bg:setLayoutComponentEnabled(true)
img_title_bg:setName("img_title_bg")
img_title_bg:setTag(73)
img_title_bg:setCascadeColorEnabled(true)
img_title_bg:setCascadeOpacityEnabled(true)
img_title_bg:setPosition(400.0000, 460.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_title_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9200)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1740)
layout:setSize({width = 800.0000, height = 87.0000})
layout:setTopMargin(-3.5000)
layout:setBottomMargin(416.5000)
img_bg:addChild(img_title_bg)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_title:setFontSize(50)
txt_title:setString([[设置]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(74)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setPosition(400.0000, 460.5500)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9211)
layout:setPercentWidth(0.1275)
layout:setPercentHeight(0.1220)
layout:setSize({width = 102.0000, height = 61.0000})
layout:setLeftMargin(349.0000)
layout:setRightMargin(349.0000)
layout:setTopMargin(8.9500)
layout:setBottomMargin(430.0500)
img_bg:addChild(txt_title)

--Create txt_bmg
local txt_bmg = ccui.Text:create()
txt_bmg:ignoreContentAdaptWithSize(true)
txt_bmg:setTextAreaSize({width = 0, height = 0})
txt_bmg:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_bmg:setFontSize(50)
txt_bmg:setString([[背景音乐]])
txt_bmg:setLayoutComponentEnabled(true)
txt_bmg:setName("txt_bmg")
txt_bmg:setTag(80)
txt_bmg:setCascadeColorEnabled(true)
txt_bmg:setCascadeOpacityEnabled(true)
txt_bmg:setPosition(226.1817, 320.5441)
txt_bmg:setTextColor({r = 243, g = 204, b = 8})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_bmg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2827)
layout:setPositionPercentY(0.6411)
layout:setPercentWidth(0.2513)
layout:setPercentHeight(0.1220)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(125.6817)
layout:setRightMargin(473.3183)
layout:setTopMargin(148.9559)
layout:setBottomMargin(290.0441)
img_bg:addChild(txt_bmg)

--Create txt_effect_music
local txt_effect_music = ccui.Text:create()
txt_effect_music:ignoreContentAdaptWithSize(true)
txt_effect_music:setTextAreaSize({width = 0, height = 0})
txt_effect_music:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_effect_music:setFontSize(50)
txt_effect_music:setString([[特效音乐]])
txt_effect_music:setLayoutComponentEnabled(true)
txt_effect_music:setName("txt_effect_music")
txt_effect_music:setTag(127)
txt_effect_music:setCascadeColorEnabled(true)
txt_effect_music:setCascadeOpacityEnabled(true)
txt_effect_music:setPosition(226.1817, 190.5438)
txt_effect_music:setTextColor({r = 243, g = 204, b = 8})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_effect_music)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2827)
layout:setPositionPercentY(0.3811)
layout:setPercentWidth(0.2513)
layout:setPercentHeight(0.1220)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(125.6817)
layout:setRightMargin(473.3183)
layout:setTopMargin(278.9562)
layout:setBottomMargin(160.0438)
img_bg:addChild(txt_effect_music)

--Create txt_version
local txt_version = ccui.Text:create()
txt_version:ignoreContentAdaptWithSize(true)
txt_version:setTextAreaSize({width = 0, height = 0})
txt_version:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_version:setFontSize(35)
txt_version:setString([[版本：1.0.0_rz10]])
txt_version:setTextHorizontalAlignment(2)
txt_version:setTextVerticalAlignment(1)
txt_version:setLayoutComponentEnabled(true)
txt_version:setName("txt_version")
txt_version:setTag(131)
txt_version:setCascadeColorEnabled(true)
txt_version:setCascadeOpacityEnabled(true)
txt_version:setAnchorPoint(1.0000, 0.5000)
txt_version:setPosition(713.4233, 60.9070)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_version)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.8918)
layout:setPositionPercentY(0.1218)
layout:setPercentWidth(0.3775)
layout:setPercentHeight(0.0860)
layout:setSize({width = 302.0000, height = 43.0000})
layout:setLeftMargin(411.4233)
layout:setRightMargin(86.5767)
layout:setTopMargin(417.5930)
layout:setBottomMargin(39.4070)
img_bg:addChild(txt_version)

--Create img_bgm
local img_bgm = ccui.ImageView:create()
img_bgm:ignoreContentAdaptWithSize(false)
img_bgm:loadTexture("assets/hall/setting/i_bgm_on.png",0)
img_bgm:setScale9Enabled(true)
img_bgm:setCapInsets({x = 21, y = 21, width = 159, height = 40})
img_bgm:setLayoutComponentEnabled(true)
img_bgm:setName("img_bgm")
img_bgm:setTag(128)
img_bgm:setCascadeColorEnabled(true)
img_bgm:setCascadeOpacityEnabled(true)
img_bgm:setPosition(562.1824, 320.5439)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bgm)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7027)
layout:setPositionPercentY(0.6411)
layout:setPercentWidth(0.2513)
layout:setPercentHeight(0.1640)
layout:setSize({width = 201.0000, height = 82.0000})
layout:setLeftMargin(461.6824)
layout:setRightMargin(137.3176)
layout:setTopMargin(138.4561)
layout:setBottomMargin(279.5439)
img_bg:addChild(img_bgm)

--Create img_effect_music
local img_effect_music = ccui.ImageView:create()
img_effect_music:ignoreContentAdaptWithSize(false)
img_effect_music:loadTexture("assets/hall/setting/i_effect_music_on.png",0)
img_effect_music:setScale9Enabled(true)
img_effect_music:setCapInsets({x = 21, y = 21, width = 159, height = 40})
img_effect_music:setLayoutComponentEnabled(true)
img_effect_music:setName("img_effect_music")
img_effect_music:setTag(129)
img_effect_music:setCascadeColorEnabled(true)
img_effect_music:setCascadeOpacityEnabled(true)
img_effect_music:setPosition(562.1824, 190.5439)
layout = ccui.LayoutComponent:bindLayoutComponent(img_effect_music)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7027)
layout:setPositionPercentY(0.3811)
layout:setPercentWidth(0.2513)
layout:setPercentHeight(0.1640)
layout:setSize({width = 201.0000, height = 82.0000})
layout:setLeftMargin(461.6824)
layout:setRightMargin(137.3176)
layout:setTopMargin(268.4561)
layout:setBottomMargin(149.5439)
img_bg:addChild(img_effect_music)

--Create img_close
local img_close = ccui.ImageView:create()
img_close:ignoreContentAdaptWithSize(false)
img_close:loadTexture("assets/common/pop_close1.png",0)
img_close:setLayoutComponentEnabled(true)
img_close:setName("img_close")
img_close:setTag(79)
img_close:setCascadeColorEnabled(true)
img_close:setCascadeOpacityEnabled(true)
img_close:setPosition(796.9600, 493.3500)
layout = ccui.LayoutComponent:bindLayoutComponent(img_close)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9962)
layout:setPositionPercentY(0.9867)
layout:setPercentWidth(0.1200)
layout:setPercentHeight(0.1940)
layout:setSize({width = 96.0000, height = 97.0000})
layout:setLeftMargin(748.9600)
layout:setRightMargin(-44.9600)
layout:setTopMargin(-41.8500)
layout:setBottomMargin(444.8500)
img_bg:addChild(img_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = setting_layer
return result;
end

return Result

