--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create room_item_node
local room_item_node=cc.Node:create()
room_item_node:setName("room_item_node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/common/item_bg.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(101)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 457.0000, height = 657.0000})
layout:setLeftMargin(-228.5000)
layout:setRightMargin(-228.5000)
layout:setTopMargin(-328.5000)
layout:setBottomMargin(-328.5000)
room_item_node:addChild(img_bg)

--Create img_bg2
local img_bg2 = ccui.ImageView:create()
img_bg2:ignoreContentAdaptWithSize(false)
img_bg2:loadTexture("assets/common/girl/girl1.png",0)
img_bg2:setLayoutComponentEnabled(true)
img_bg2:setName("img_bg2")
img_bg2:setTag(126)
img_bg2:setCascadeColorEnabled(true)
img_bg2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg2)
layout:setSize({width = 407.0000, height = 566.0000})
layout:setLeftMargin(-203.5000)
layout:setRightMargin(-203.5000)
layout:setTopMargin(-283.0000)
layout:setBottomMargin(-283.0000)
room_item_node:addChild(img_bg2)

--Create txt_base0
local txt_base0 = ccui.Text:create()
txt_base0:ignoreContentAdaptWithSize(true)
txt_base0:setTextAreaSize({width = 0, height = 0})
txt_base0:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_base0:setFontSize(50)
txt_base0:setString([[底注]])
txt_base0:setLayoutComponentEnabled(true)
txt_base0:setName("txt_base0")
txt_base0:setTag(125)
txt_base0:setCascadeColorEnabled(true)
txt_base0:setCascadeOpacityEnabled(true)
txt_base0:setPosition(-139.0000, -64.5488)
txt_base0:setTextColor({r = 203, g = 159, b = 49})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_base0)
layout:setSize({width = 101.0000, height = 61.0000})
layout:setLeftMargin(-189.5000)
layout:setRightMargin(88.5000)
layout:setTopMargin(34.0488)
layout:setBottomMargin(-95.0488)
room_item_node:addChild(txt_base0)

--Create txt_cost0
local txt_cost0 = ccui.Text:create()
txt_cost0:ignoreContentAdaptWithSize(true)
txt_cost0:setTextAreaSize({width = 0, height = 0})
txt_cost0:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_cost0:setFontSize(50)
txt_cost0:setString([[入场]])
txt_cost0:setLayoutComponentEnabled(true)
txt_cost0:setName("txt_cost0")
txt_cost0:setTag(21)
txt_cost0:setCascadeColorEnabled(true)
txt_cost0:setCascadeOpacityEnabled(true)
txt_cost0:setPosition(-139.0000, -140.0000)
txt_cost0:setTextColor({r = 203, g = 159, b = 49})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_cost0)
layout:setSize({width = 100.0000, height = 61.0000})
layout:setLeftMargin(-189.0000)
layout:setRightMargin(89.0000)
layout:setTopMargin(109.5000)
layout:setBottomMargin(-170.5000)
room_item_node:addChild(txt_cost0)

--Create txt_room_name
local txt_room_name = ccui.Text:create()
txt_room_name:ignoreContentAdaptWithSize(true)
txt_room_name:setTextAreaSize({width = 0, height = 0})
txt_room_name:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_room_name:setFontSize(80)
txt_room_name:setString([[初级场]])
txt_room_name:setLayoutComponentEnabled(true)
txt_room_name:setName("txt_room_name")
txt_room_name:setTag(103)
txt_room_name:setCascadeColorEnabled(true)
txt_room_name:setCascadeOpacityEnabled(true)
txt_room_name:setPosition(0.0000, -236.0000)
txt_room_name:setTextColor({r = 243, g = 128, b = 8})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_room_name)
layout:setSize({width = 238.0000, height = 98.0000})
layout:setLeftMargin(-119.0000)
layout:setRightMargin(-119.0000)
layout:setTopMargin(187.0000)
layout:setBottomMargin(-285.0000)
room_item_node:addChild(txt_room_name)

--Create txt_base_score
local txt_base_score = ccui.Text:create()
txt_base_score:ignoreContentAdaptWithSize(true)
txt_base_score:setTextAreaSize({width = 0, height = 0})
txt_base_score:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_base_score:setFontSize(45)
txt_base_score:setString([[88,888金币]])
txt_base_score:setLayoutComponentEnabled(true)
txt_base_score:setName("txt_base_score")
txt_base_score:setTag(104)
txt_base_score:setCascadeColorEnabled(true)
txt_base_score:setCascadeOpacityEnabled(true)
txt_base_score:setPosition(54.0000, -64.5484)
txt_base_score:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_base_score)
layout:setSize({width = 266.0000, height = 55.0000})
layout:setLeftMargin(-79.0000)
layout:setRightMargin(-187.0000)
layout:setTopMargin(37.0484)
layout:setBottomMargin(-92.0484)
room_item_node:addChild(txt_base_score)

--Create txt_min_score
local txt_min_score = ccui.Text:create()
txt_min_score:ignoreContentAdaptWithSize(true)
txt_min_score:setTextAreaSize({width = 0, height = 0})
txt_min_score:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_min_score:setFontSize(45)
txt_min_score:setString([[88,888金币]])
txt_min_score:setLayoutComponentEnabled(true)
txt_min_score:setName("txt_min_score")
txt_min_score:setTag(22)
txt_min_score:setCascadeColorEnabled(true)
txt_min_score:setCascadeOpacityEnabled(true)
txt_min_score:setPosition(54.0000, -140.0000)
txt_min_score:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_min_score)
layout:setSize({width = 266.0000, height = 55.0000})
layout:setLeftMargin(-79.0000)
layout:setRightMargin(-187.0000)
layout:setTopMargin(112.5000)
layout:setBottomMargin(-167.5000)
room_item_node:addChild(txt_min_score)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = room_item_node
return result;
end

return Result

