--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create login_scene
local login_scene=cc.Node:create()
login_scene:setName("login_scene")

--Create img_login_bg
local img_login_bg = ccui.ImageView:create()
img_login_bg:ignoreContentAdaptWithSize(false)
img_login_bg:loadTexture("assets/login/login_bg.jpg",0)
img_login_bg:setLayoutComponentEnabled(true)
img_login_bg:setName("img_login_bg")
img_login_bg:setTag(6)
img_login_bg:setCascadeColorEnabled(true)
img_login_bg:setCascadeOpacityEnabled(true)
img_login_bg:setPosition(960.0000, 540.0320)
layout = ccui.LayoutComponent:bindLayoutComponent(img_login_bg)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.8438)
layout:setPercentWidth(2.0000)
layout:setPercentHeight(1.6875)
layout:setSize({width = 1920.0000, height = 1080.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-440.0320)
layout:setBottomMargin(0.0320)
login_scene:addChild(img_login_bg)

--Create btn_login
local btn_login = ccui.Button:create()
btn_login:ignoreContentAdaptWithSize(false)
btn_login:loadTextureNormal("assets/common/btn_common_purple.png",0)
btn_login:loadTexturePressed("assets/common/btn_common_purple.png",0)
btn_login:loadTextureDisabled("Default/Button_Disable.png",0)
btn_login:setTitleFontSize(52)
btn_login:setTitleText("登陆")
btn_login:setTitleColor({r = 65, g = 65, b = 70})
btn_login:setScale9Enabled(true)
btn_login:setCapInsets({x = 15, y = 11, width = 363, height = 91})
btn_login:setLayoutComponentEnabled(true)
btn_login:setName("btn_login")
btn_login:setTag(3)
btn_login:setCascadeColorEnabled(true)
btn_login:setCascadeOpacityEnabled(true)
btn_login:setPosition(960.0000, 260.1169)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_login)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.4064)
layout:setPercentWidth(0.4094)
layout:setPercentHeight(0.1766)
layout:setSize({width = 393.0000, height = 113.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(763.5000)
layout:setRightMargin(-196.5000)
layout:setTopMargin(323.3831)
layout:setBottomMargin(203.6169)
login_scene:addChild(btn_login)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = login_scene
return result;
end

return Result

