--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create node_player_head
local node_player_head=cc.Node:create()
node_player_head:setName("node_player_head")

--Create txt_name
local txt_name = ccui.Text:create()
txt_name:ignoreContentAdaptWithSize(true)
txt_name:setTextAreaSize({width = 0, height = 0})
txt_name:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_name:setFontSize(38)
txt_name:setString([[西边小姐姐]])
txt_name:setLayoutComponentEnabled(true)
txt_name:setName("txt_name")
txt_name:setTag(84)
txt_name:setCascadeColorEnabled(true)
txt_name:setCascadeOpacityEnabled(true)
txt_name:setAnchorPoint(0.0000, 0.5000)
txt_name:setPosition(110.0000, 71.6383)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_name)
layout:setSize({width = 192.0000, height = 46.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(-302.0000)
layout:setTopMargin(-94.6383)
layout:setBottomMargin(48.6383)
node_player_head:addChild(txt_name)

--Create txt_vip_level
local txt_vip_level = ccui.Text:create()
txt_vip_level:ignoreContentAdaptWithSize(true)
txt_vip_level:setTextAreaSize({width = 0, height = 0})
txt_vip_level:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_vip_level:setFontSize(38)
txt_vip_level:setString([[lv:10]])
txt_vip_level:setLayoutComponentEnabled(true)
txt_vip_level:setName("txt_vip_level")
txt_vip_level:setTag(85)
txt_vip_level:setCascadeColorEnabled(true)
txt_vip_level:setCascadeOpacityEnabled(true)
txt_vip_level:setAnchorPoint(0.0000, 0.5000)
txt_vip_level:setPosition(110.0000, -49.3658)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_vip_level)
layout:setSize({width = 97.0000, height = 46.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(-207.0000)
layout:setTopMargin(26.3658)
layout:setBottomMargin(-72.3658)
node_player_head:addChild(txt_vip_level)

--Create txt_level_name
local txt_level_name = ccui.Text:create()
txt_level_name:ignoreContentAdaptWithSize(true)
txt_level_name:setTextAreaSize({width = 0, height = 0})
txt_level_name:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_level_name:setFontSize(38)
txt_level_name:setString([[一级牌手]])
txt_level_name:setLayoutComponentEnabled(true)
txt_level_name:setName("txt_level_name")
txt_level_name:setTag(86)
txt_level_name:setCascadeColorEnabled(true)
txt_level_name:setCascadeOpacityEnabled(true)
txt_level_name:setAnchorPoint(0.0000, 0.5000)
txt_level_name:setPosition(110.0000, 12.3381)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_level_name)
layout:setSize({width = 154.0000, height = 46.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(-264.0000)
layout:setTopMargin(-35.3381)
layout:setBottomMargin(-10.6619)
node_player_head:addChild(txt_level_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = node_player_head
return result;
end

return Result

