--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create hall_middle_node
local hall_middle_node=cc.Node:create()
hall_middle_node:setName("hall_middle_node")

--Create node_left
local node_left=cc.Node:create()
node_left:setName("node_left")
node_left:setTag(20)
node_left:setCascadeColorEnabled(true)
node_left:setCascadeOpacityEnabled(true)
node_left:setPosition(-700.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_left)
layout:setLeftMargin(-700.0000)
layout:setRightMargin(700.0000)
hall_middle_node:addChild(node_left)

--Create img_left_bg
local img_left_bg = ccui.ImageView:create()
img_left_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_left_bg:loadTexture("hall_create_room_bg.png",1)
img_left_bg:setLayoutComponentEnabled(true)
img_left_bg:setName("img_left_bg")
img_left_bg:setTag(90)
img_left_bg:setCascadeColorEnabled(true)
img_left_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_left_bg)
layout:setSize({width = 439.0000, height = 605.0000})
layout:setLeftMargin(-219.5000)
layout:setRightMargin(-219.5000)
layout:setTopMargin(-302.5000)
layout:setBottomMargin(-302.5000)
node_left:addChild(img_left_bg)

--Create img_left
local img_left = ccui.ImageView:create()
img_left:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_left:loadTexture("hall_girl.png",1)
img_left:setLayoutComponentEnabled(true)
img_left:setName("img_left")
img_left:setTag(23)
img_left:setCascadeColorEnabled(true)
img_left:setCascadeOpacityEnabled(true)
img_left:setPosition(0.0000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_left)
layout:setSize({width = 460.0000, height = 590.0000})
layout:setLeftMargin(-230.0000)
layout:setRightMargin(-230.0000)
layout:setTopMargin(-331.0000)
layout:setBottomMargin(-259.0000)
node_left:addChild(img_left)

--Create node_middle
local node_middle=cc.Node:create()
node_middle:setName("node_middle")
node_middle:setTag(21)
node_middle:setCascadeColorEnabled(true)
node_middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_middle)
hall_middle_node:addChild(node_middle)

--Create img_middle
local img_middle = ccui.ImageView:create()
img_middle:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_middle:loadTexture("hall_create_room_bg.png",1)
img_middle:setLayoutComponentEnabled(true)
img_middle:setName("img_middle")
img_middle:setTag(23)
img_middle:setCascadeColorEnabled(true)
img_middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_middle)
layout:setSize({width = 439.0000, height = 605.0000})
layout:setLeftMargin(-219.5000)
layout:setRightMargin(-219.5000)
layout:setTopMargin(-302.5000)
layout:setBottomMargin(-302.5000)
node_middle:addChild(img_middle)

--Create img_mahjong
local img_mahjong = ccui.ImageView:create()
img_mahjong:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_mahjong:loadTexture("hall_mahjong.png",1)
img_mahjong:setLayoutComponentEnabled(true)
img_mahjong:setName("img_mahjong")
img_mahjong:setTag(49)
img_mahjong:setCascadeColorEnabled(true)
img_mahjong:setCascadeOpacityEnabled(true)
img_mahjong:setPosition(-6.8324, 86.7969)
layout = ccui.LayoutComponent:bindLayoutComponent(img_mahjong)
layout:setSize({width = 388.0000, height = 342.0000})
layout:setLeftMargin(-200.8324)
layout:setRightMargin(-187.1676)
layout:setTopMargin(-257.7969)
layout:setBottomMargin(-84.2031)
node_middle:addChild(img_mahjong)

--Create img_dice1
local img_dice1 = ccui.ImageView:create()
img_dice1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_dice1:loadTexture("hall_doce2.png",1)
img_dice1:setLayoutComponentEnabled(true)
img_dice1:setName("img_dice1")
img_dice1:setTag(50)
img_dice1:setCascadeColorEnabled(true)
img_dice1:setCascadeOpacityEnabled(true)
img_dice1:setPosition(-131.1272, 149.5321)
layout = ccui.LayoutComponent:bindLayoutComponent(img_dice1)
layout:setSize({width = 127.0000, height = 139.0000})
layout:setLeftMargin(-194.6272)
layout:setRightMargin(67.6272)
layout:setTopMargin(-219.0321)
layout:setBottomMargin(80.0321)
node_middle:addChild(img_dice1)

--Create img_dice2
local img_dice2 = ccui.ImageView:create()
img_dice2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_dice2:loadTexture("hall_doce1.png",1)
img_dice2:setLayoutComponentEnabled(true)
img_dice2:setName("img_dice2")
img_dice2:setTag(51)
img_dice2:setCascadeColorEnabled(true)
img_dice2:setCascadeOpacityEnabled(true)
img_dice2:setPosition(134.3845, 38.8164)
layout = ccui.LayoutComponent:bindLayoutComponent(img_dice2)
layout:setSize({width = 130.0000, height = 135.0000})
layout:setLeftMargin(69.3845)
layout:setRightMargin(-199.3845)
layout:setTopMargin(-106.3164)
layout:setBottomMargin(-28.6836)
node_middle:addChild(img_dice2)

--Create node_right
local node_right=cc.Node:create()
node_right:setName("node_right")
node_right:setTag(22)
node_right:setCascadeColorEnabled(true)
node_right:setCascadeOpacityEnabled(true)
node_right:setPosition(700.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_right)
layout:setLeftMargin(700.0000)
layout:setRightMargin(-700.0000)
hall_middle_node:addChild(node_right)

--Create img_right
local img_right = ccui.ImageView:create()
img_right:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_right:loadTexture("hall_join_room_bg.png",1)
img_right:setLayoutComponentEnabled(true)
img_right:setName("img_right")
img_right:setTag(24)
img_right:setCascadeColorEnabled(true)
img_right:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_right)
layout:setSize({width = 439.0000, height = 605.0000})
layout:setLeftMargin(-219.5000)
layout:setRightMargin(-219.5000)
layout:setTopMargin(-302.5000)
layout:setBottomMargin(-302.5000)
node_right:addChild(img_right)

--Create img_key
local img_key = ccui.ImageView:create()
img_key:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_key:loadTexture("hall_key.png",1)
img_key:setLayoutComponentEnabled(true)
img_key:setName("img_key")
img_key:setTag(54)
img_key:setCascadeColorEnabled(true)
img_key:setCascadeOpacityEnabled(true)
img_key:setPosition(6.5346, 87.3261)
layout = ccui.LayoutComponent:bindLayoutComponent(img_key)
layout:setSize({width = 308.0000, height = 381.0000})
layout:setLeftMargin(-147.4654)
layout:setRightMargin(-160.5346)
layout:setTopMargin(-277.8260)
layout:setBottomMargin(-103.1740)
node_right:addChild(img_key)

--Create img_mahjong1
local img_mahjong1 = ccui.ImageView:create()
img_mahjong1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_mahjong1:loadTexture("hall_mahjong1.png",1)
img_mahjong1:setLayoutComponentEnabled(true)
img_mahjong1:setName("img_mahjong1")
img_mahjong1:setTag(52)
img_mahjong1:setCascadeColorEnabled(true)
img_mahjong1:setCascadeOpacityEnabled(true)
img_mahjong1:setPosition(-127.6623, 58.8313)
layout = ccui.LayoutComponent:bindLayoutComponent(img_mahjong1)
layout:setSize({width = 126.0000, height = 153.0000})
layout:setLeftMargin(-190.6623)
layout:setRightMargin(64.6623)
layout:setTopMargin(-135.3313)
layout:setBottomMargin(-17.6687)
node_right:addChild(img_mahjong1)

--Create img_mahjong2
local img_mahjong2 = ccui.ImageView:create()
img_mahjong2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_middle.plist")
img_mahjong2:loadTexture("hall_mahjong2.png",1)
img_mahjong2:setLayoutComponentEnabled(true)
img_mahjong2:setName("img_mahjong2")
img_mahjong2:setTag(53)
img_mahjong2:setCascadeColorEnabled(true)
img_mahjong2:setCascadeOpacityEnabled(true)
img_mahjong2:setPosition(138.8906, 106.7120)
layout = ccui.LayoutComponent:bindLayoutComponent(img_mahjong2)
layout:setSize({width = 126.0000, height = 148.0000})
layout:setLeftMargin(75.8906)
layout:setRightMargin(-201.8906)
layout:setTopMargin(-180.7120)
layout:setBottomMargin(32.7120)
node_right:addChild(img_mahjong2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = hall_middle_node
return result;
end

return Result

