--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create head_node
local head_node=cc.Node:create()
head_node:setName("head_node")

--Create img_head
local img_head = ccui.ImageView:create()
img_head:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/common/plist/head.plist")
img_head:loadTexture("woman_4.png",1)
img_head:setLayoutComponentEnabled(true)
img_head:setName("img_head")
img_head:setTag(20)
img_head:setCascadeColorEnabled(true)
img_head:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_head)
layout:setSize({width = 230.0000, height = 230.0000})
layout:setLeftMargin(-115.0000)
layout:setRightMargin(-115.0000)
layout:setTopMargin(-115.0000)
layout:setBottomMargin(-115.0000)
head_node:addChild(img_head)

--Create txt_name
local txt_name = ccui.Text:create()
txt_name:ignoreContentAdaptWithSize(true)
txt_name:setTextAreaSize({width = 0, height = 0})
txt_name:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_name:setFontSize(36)
txt_name:setString([[漂亮小姐姐]])
txt_name:setTextHorizontalAlignment(1)
txt_name:setTextVerticalAlignment(1)
txt_name:setLayoutComponentEnabled(true)
txt_name:setName("txt_name")
txt_name:setTag(21)
txt_name:setCascadeColorEnabled(true)
txt_name:setCascadeOpacityEnabled(true)
txt_name:setPosition(0.0000, -93.0680)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_name)
layout:setSize({width = 181.0000, height = 44.0000})
layout:setLeftMargin(-90.5000)
layout:setRightMargin(-90.5000)
layout:setTopMargin(71.0680)
layout:setBottomMargin(-115.0680)
head_node:addChild(txt_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = head_node
return result;
end

return Result

