--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create hall_scene
local hall_scene=cc.Node:create()
hall_scene:setName("hall_scene")

--Create img_hall_bg
local img_hall_bg = ccui.ImageView:create()
img_hall_bg:ignoreContentAdaptWithSize(false)
img_hall_bg:loadTexture("assets/hall/hall_bg.jpg",0)
img_hall_bg:setLayoutComponentEnabled(true)
img_hall_bg:setName("img_hall_bg")
img_hall_bg:setTag(5)
img_hall_bg:setCascadeColorEnabled(true)
img_hall_bg:setCascadeOpacityEnabled(true)
img_hall_bg:setPosition(960.0000, 540.0320)
layout = ccui.LayoutComponent:bindLayoutComponent(img_hall_bg)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.8438)
layout:setPercentWidth(2.0000)
layout:setPercentHeight(2.0000)
layout:setSize({width = 1920.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-540.0320)
layout:setBottomMargin(-99.9680)
hall_scene:addChild(img_hall_bg)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = hall_scene
return result;
end

return Result

