--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create store_layer
local store_layer=cc.Node:create()
store_layer:setName("store_layer")
layout = ccui.LayoutComponent:bindLayoutComponent(store_layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/hall/popup_bg1.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(89)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(960.0000, 486.3633)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4503)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.7407)
layout:setSize({width = 1600.0000, height = 800.0000})
layout:setLeftMargin(160.0000)
layout:setRightMargin(160.0000)
layout:setTopMargin(193.6367)
layout:setBottomMargin(86.3633)
store_layer:addChild(img_bg)

--Create lv_goods
local lv_goods = ccui.ListView:create()
lv_goods:setDirection(2)
lv_goods:setGravity(3)
lv_goods:ignoreContentAdaptWithSize(false)
lv_goods:setClippingEnabled(true)
lv_goods:setBackGroundColorOpacity(102)
lv_goods:setLayoutComponentEnabled(true)
lv_goods:setName("lv_goods")
lv_goods:setTag(99)
lv_goods:setCascadeColorEnabled(true)
lv_goods:setCascadeOpacityEnabled(true)
lv_goods:setAnchorPoint(0.5000, 0.5000)
lv_goods:setPosition(800.0000, 400.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lv_goods)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9688)
layout:setPercentHeight(0.8125)
layout:setSize({width = 1550.0000, height = 650.0000})
layout:setLeftMargin(25.0000)
layout:setRightMargin(25.0000)
layout:setTopMargin(75.0000)
layout:setBottomMargin(75.0000)
img_bg:addChild(lv_goods)

--Create img_tab1
local img_tab1 = ccui.ImageView:create()
img_tab1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_tab1:loadTexture("hall_title_bg.png",1)
img_tab1:setFlippedY(true)
img_tab1:setLayoutComponentEnabled(true)
img_tab1:setName("img_tab1")
img_tab1:setTag(90)
img_tab1:setCascadeColorEnabled(true)
img_tab1:setCascadeOpacityEnabled(true)
img_tab1:setPosition(545.5506, 949.7149)
layout = ccui.LayoutComponent:bindLayoutComponent(img_tab1)
layout:setPositionPercentX(0.2841)
layout:setPositionPercentY(0.8794)
layout:setPercentWidth(0.3042)
layout:setPercentHeight(0.1259)
layout:setSize({width = 584.0000, height = 136.0000})
layout:setLeftMargin(253.5506)
layout:setRightMargin(1082.4490)
layout:setTopMargin(62.2851)
layout:setBottomMargin(881.7149)
store_layer:addChild(img_tab1)

--Create img_tab2
local img_tab2 = ccui.ImageView:create()
img_tab2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_tab2:loadTexture("hall_title_bg.png",1)
img_tab2:setFlippedY(true)
img_tab2:setLayoutComponentEnabled(true)
img_tab2:setName("img_tab2")
img_tab2:setTag(91)
img_tab2:setCascadeColorEnabled(true)
img_tab2:setCascadeOpacityEnabled(true)
img_tab2:setPosition(966.8567, 949.7149)
layout = ccui.LayoutComponent:bindLayoutComponent(img_tab2)
layout:setPositionPercentX(0.5036)
layout:setPositionPercentY(0.8794)
layout:setPercentWidth(0.3042)
layout:setPercentHeight(0.1259)
layout:setSize({width = 584.0000, height = 136.0000})
layout:setLeftMargin(674.8567)
layout:setRightMargin(661.1433)
layout:setTopMargin(62.2851)
layout:setBottomMargin(881.7149)
store_layer:addChild(img_tab2)

--Create img_tab3
local img_tab3 = ccui.ImageView:create()
img_tab3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_tab3:loadTexture("hall_title_bg.png",1)
img_tab3:setFlippedY(true)
img_tab3:setLayoutComponentEnabled(true)
img_tab3:setName("img_tab3")
img_tab3:setTag(92)
img_tab3:setCascadeColorEnabled(true)
img_tab3:setCascadeOpacityEnabled(true)
img_tab3:setPosition(1383.8590, 949.7149)
layout = ccui.LayoutComponent:bindLayoutComponent(img_tab3)
layout:setPositionPercentX(0.7208)
layout:setPositionPercentY(0.8794)
layout:setPercentWidth(0.3042)
layout:setPercentHeight(0.1259)
layout:setSize({width = 584.0000, height = 136.0000})
layout:setLeftMargin(1091.8590)
layout:setRightMargin(244.1415)
layout:setTopMargin(62.2851)
layout:setBottomMargin(881.7149)
store_layer:addChild(img_tab3)

--Create txt_gold
local txt_gold = ccui.Text:create()
txt_gold:ignoreContentAdaptWithSize(true)
txt_gold:setTextAreaSize({width = 0, height = 0})
txt_gold:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_gold:setFontSize(50)
txt_gold:setString([[金币购买]])
txt_gold:setLayoutComponentEnabled(true)
txt_gold:setName("txt_gold")
txt_gold:setTag(93)
txt_gold:setCascadeColorEnabled(true)
txt_gold:setCascadeOpacityEnabled(true)
txt_gold:setPosition(534.5092, 934.7150)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_gold)
layout:setPositionPercentX(0.2784)
layout:setPositionPercentY(0.8655)
layout:setPercentWidth(0.1047)
layout:setPercentHeight(0.0565)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(434.0092)
layout:setRightMargin(1284.9910)
layout:setTopMargin(114.7850)
layout:setBottomMargin(904.2150)
store_layer:addChild(txt_gold)

--Create txt_diamond
local txt_diamond = ccui.Text:create()
txt_diamond:ignoreContentAdaptWithSize(true)
txt_diamond:setTextAreaSize({width = 0, height = 0})
txt_diamond:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_diamond:setFontSize(50)
txt_diamond:setString([[钻石购买]])
txt_diamond:setLayoutComponentEnabled(true)
txt_diamond:setName("txt_diamond")
txt_diamond:setTag(94)
txt_diamond:setCascadeColorEnabled(true)
txt_diamond:setCascadeOpacityEnabled(true)
txt_diamond:setPosition(960.6055, 934.7150)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_diamond)
layout:setPositionPercentX(0.5003)
layout:setPositionPercentY(0.8655)
layout:setPercentWidth(0.1047)
layout:setPercentHeight(0.0565)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(860.1055)
layout:setRightMargin(858.8945)
layout:setTopMargin(114.7850)
layout:setBottomMargin(904.2150)
store_layer:addChild(txt_diamond)

--Create txt_prop
local txt_prop = ccui.Text:create()
txt_prop:ignoreContentAdaptWithSize(true)
txt_prop:setTextAreaSize({width = 0, height = 0})
txt_prop:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_prop:setFontSize(50)
txt_prop:setString([[道具购买]])
txt_prop:setLayoutComponentEnabled(true)
txt_prop:setName("txt_prop")
txt_prop:setTag(95)
txt_prop:setCascadeColorEnabled(true)
txt_prop:setCascadeOpacityEnabled(true)
txt_prop:setPosition(1384.6430, 934.7150)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_prop)
layout:setPositionPercentX(0.7212)
layout:setPositionPercentY(0.8655)
layout:setPercentWidth(0.1047)
layout:setPercentHeight(0.0565)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(1284.1430)
layout:setRightMargin(434.8566)
layout:setTopMargin(114.7850)
layout:setBottomMargin(904.2150)
store_layer:addChild(txt_prop)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = store_layer
return result;
end

return Result

