--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create room_item_node
local room_item_node=cc.Node:create()
room_item_node:setName("room_item_node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/common/item_bg.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(101)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 457.0000, height = 657.0000})
layout:setLeftMargin(-228.5000)
layout:setRightMargin(-228.5000)
layout:setTopMargin(-328.5000)
layout:setBottomMargin(-328.5000)
room_item_node:addChild(img_bg)

--Create img_bg2
local img_bg2 = ccui.ImageView:create()
img_bg2:ignoreContentAdaptWithSize(false)
img_bg2:loadTexture("assets/common/girl/girl1.png",0)
img_bg2:setLayoutComponentEnabled(true)
img_bg2:setName("img_bg2")
img_bg2:setTag(126)
img_bg2:setCascadeColorEnabled(true)
img_bg2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg2)
layout:setSize({width = 407.0000, height = 566.0000})
layout:setLeftMargin(-203.5000)
layout:setRightMargin(-203.5000)
layout:setTopMargin(-283.0000)
layout:setBottomMargin(-283.0000)
room_item_node:addChild(img_bg2)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_title:setFontSize(80)
txt_title:setString([[初级场]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(103)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setPosition(0.0000, -248.0400)
txt_title:setTextColor({r = 243, g = 204, b = 8})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setSize({width = 238.0000, height = 98.0000})
layout:setLeftMargin(-119.0000)
layout:setRightMargin(-119.0000)
layout:setTopMargin(199.0400)
layout:setBottomMargin(-297.0400)
room_item_node:addChild(txt_title)

--Create txt_cost0
local txt_cost0 = ccui.Text:create()
txt_cost0:ignoreContentAdaptWithSize(true)
txt_cost0:setTextAreaSize({width = 0, height = 0})
txt_cost0:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_cost0:setFontSize(50)
txt_cost0:setString([[底注]])
txt_cost0:setLayoutComponentEnabled(true)
txt_cost0:setName("txt_cost0")
txt_cost0:setTag(125)
txt_cost0:setCascadeColorEnabled(true)
txt_cost0:setCascadeOpacityEnabled(true)
txt_cost0:setPosition(-141.7172, -130.0000)
txt_cost0:setTextColor({r = 203, g = 159, b = 49})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_cost0)
layout:setSize({width = 101.0000, height = 61.0000})
layout:setLeftMargin(-192.2172)
layout:setRightMargin(91.2172)
layout:setTopMargin(99.5000)
layout:setBottomMargin(-160.5000)
room_item_node:addChild(txt_cost0)

--Create txt_cost
local txt_cost = ccui.Text:create()
txt_cost:ignoreContentAdaptWithSize(true)
txt_cost:setTextAreaSize({width = 0, height = 0})
txt_cost:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_cost:setFontSize(45)
txt_cost:setString([[68,000金币]])
txt_cost:setLayoutComponentEnabled(true)
txt_cost:setName("txt_cost")
txt_cost:setTag(104)
txt_cost:setCascadeColorEnabled(true)
txt_cost:setCascadeOpacityEnabled(true)
txt_cost:setPosition(52.7940, -130.0000)
txt_cost:setTextColor({r = 228, g = 96, b = 23})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_cost)
layout:setSize({width = 266.0000, height = 55.0000})
layout:setLeftMargin(-80.2060)
layout:setRightMargin(-185.7940)
layout:setTopMargin(102.5000)
layout:setBottomMargin(-157.5000)
room_item_node:addChild(txt_cost)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = room_item_node
return result;
end

return Result

