--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create mahjong_node
local mahjong_node=cc.Node:create()
mahjong_node:setName("mahjong_node")

--Create img_bottom_bg1
local img_bottom_bg1 = ccui.ImageView:create()
img_bottom_bg1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_bottom_bg1:loadTexture("mj_opposite_visible.png",1)
img_bottom_bg1:setLayoutComponentEnabled(true)
img_bottom_bg1:setName("img_bottom_bg1")
img_bottom_bg1:setTag(27)
img_bottom_bg1:setCascadeColorEnabled(true)
img_bottom_bg1:setCascadeOpacityEnabled(true)
img_bottom_bg1:setPosition(-49.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bottom_bg1)
layout:setSize({width = 53.0000, height = 73.0000})
layout:setLeftMargin(-75.5000)
layout:setRightMargin(22.5000)
layout:setTopMargin(-36.5000)
layout:setBottomMargin(-36.5000)
mahjong_node:addChild(img_bottom_bg1)

--Create img_bottom_bg2
local img_bottom_bg2 = ccui.ImageView:create()
img_bottom_bg2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_bottom_bg2:loadTexture("mj_opposite_visible.png",1)
img_bottom_bg2:setLayoutComponentEnabled(true)
img_bottom_bg2:setName("img_bottom_bg2")
img_bottom_bg2:setTag(12)
img_bottom_bg2:setCascadeColorEnabled(true)
img_bottom_bg2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bottom_bg2)
layout:setSize({width = 53.0000, height = 73.0000})
layout:setLeftMargin(-26.5000)
layout:setRightMargin(-26.5000)
layout:setTopMargin(-36.5000)
layout:setBottomMargin(-36.5000)
mahjong_node:addChild(img_bottom_bg2)

--Create img_bottom_bg3
local img_bottom_bg3 = ccui.ImageView:create()
img_bottom_bg3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_bottom_bg3:loadTexture("mj_opposite_visible.png",1)
img_bottom_bg3:setLayoutComponentEnabled(true)
img_bottom_bg3:setName("img_bottom_bg3")
img_bottom_bg3:setTag(28)
img_bottom_bg3:setCascadeColorEnabled(true)
img_bottom_bg3:setCascadeOpacityEnabled(true)
img_bottom_bg3:setPosition(49.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bottom_bg3)
layout:setSize({width = 53.0000, height = 73.0000})
layout:setLeftMargin(22.5000)
layout:setRightMargin(-75.5000)
layout:setTopMargin(-36.5000)
layout:setBottomMargin(-36.5000)
mahjong_node:addChild(img_bottom_bg3)

--Create img_top_bg
local img_top_bg = ccui.ImageView:create()
img_top_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_top_bg:loadTexture("mj_opposite_visible.png",1)
img_top_bg:setLayoutComponentEnabled(true)
img_top_bg:setName("img_top_bg")
img_top_bg:setTag(9)
img_top_bg:setCascadeColorEnabled(true)
img_top_bg:setCascadeOpacityEnabled(true)
img_top_bg:setPosition(0.0000, 19.2782)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_bg)
layout:setSize({width = 53.0000, height = 73.0000})
layout:setLeftMargin(-26.5000)
layout:setRightMargin(-26.5000)
layout:setTopMargin(-55.7782)
layout:setBottomMargin(-17.2218)
mahjong_node:addChild(img_top_bg)

--Create img_top_fg1
local img_top_fg1 = ccui.ImageView:create()
img_top_fg1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_top_fg1:loadTexture("character_9.png",1)
img_top_fg1:setFlippedX(true)
img_top_fg1:setFlippedY(true)
img_top_fg1:setLayoutComponentEnabled(true)
img_top_fg1:setName("img_top_fg1")
img_top_fg1:setTag(29)
img_top_fg1:setCascadeColorEnabled(true)
img_top_fg1:setCascadeOpacityEnabled(true)
img_top_fg1:setPosition(-49.0000, 10.0000)
img_top_fg1:setScaleX(0.4500)
img_top_fg1:setScaleY(0.3600)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_fg1)
layout:setSize({width = 102.0000, height = 124.0000})
layout:setLeftMargin(-100.0000)
layout:setRightMargin(-2.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-52.0000)
mahjong_node:addChild(img_top_fg1)

--Create img_top_fg2
local img_top_fg2 = ccui.ImageView:create()
img_top_fg2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_top_fg2:loadTexture("character_9.png",1)
img_top_fg2:setFlippedX(true)
img_top_fg2:setFlippedY(true)
img_top_fg2:setLayoutComponentEnabled(true)
img_top_fg2:setName("img_top_fg2")
img_top_fg2:setTag(10)
img_top_fg2:setCascadeColorEnabled(true)
img_top_fg2:setCascadeOpacityEnabled(true)
img_top_fg2:setPosition(-0.0002, 29.4042)
img_top_fg2:setScaleX(0.4500)
img_top_fg2:setScaleY(0.3600)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_fg2)
layout:setSize({width = 102.0000, height = 124.0000})
layout:setLeftMargin(-51.0002)
layout:setRightMargin(-50.9998)
layout:setTopMargin(-91.4042)
layout:setBottomMargin(-32.5958)
mahjong_node:addChild(img_top_fg2)

--Create img_top_fg3
local img_top_fg3 = ccui.ImageView:create()
img_top_fg3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/room/plist/cards.plist")
img_top_fg3:loadTexture("character_9.png",1)
img_top_fg3:setFlippedX(true)
img_top_fg3:setFlippedY(true)
img_top_fg3:setLayoutComponentEnabled(true)
img_top_fg3:setName("img_top_fg3")
img_top_fg3:setTag(30)
img_top_fg3:setCascadeColorEnabled(true)
img_top_fg3:setCascadeOpacityEnabled(true)
img_top_fg3:setPosition(49.0000, 10.0000)
img_top_fg3:setScaleX(0.4500)
img_top_fg3:setScaleY(0.3600)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_fg3)
layout:setSize({width = 102.0000, height = 124.0000})
layout:setLeftMargin(-2.0000)
layout:setRightMargin(-100.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-52.0000)
mahjong_node:addChild(img_top_fg3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = mahjong_node
return result;
end

return Result

