--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create node_store_item
local node_store_item=cc.Node:create()
node_store_item:setName("node_store_item")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/common/item_bg.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(101)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 457.0000, height = 657.0000})
layout:setLeftMargin(-228.5000)
layout:setRightMargin(-228.5000)
layout:setTopMargin(-328.5000)
layout:setBottomMargin(-328.5000)
node_store_item:addChild(img_bg)

--Create img_item
local img_item = ccui.ImageView:create()
img_item:ignoreContentAdaptWithSize(false)
img_item:loadTexture("assets/common/i_store_gold.png",0)
img_item:setLayoutComponentEnabled(true)
img_item:setName("img_item")
img_item:setTag(102)
img_item:setCascadeColorEnabled(true)
img_item:setCascadeOpacityEnabled(true)
img_item:setPosition(0.0000, 29.8557)
layout = ccui.LayoutComponent:bindLayoutComponent(img_item)
layout:setSize({width = 154.0000, height = 154.0000})
layout:setLeftMargin(-77.0000)
layout:setRightMargin(-77.0000)
layout:setTopMargin(-106.8557)
layout:setBottomMargin(-47.1443)
node_store_item:addChild(img_item)

--Create txt_price
local txt_price = ccui.Text:create()
txt_price:ignoreContentAdaptWithSize(true)
txt_price:setTextAreaSize({width = 0, height = 0})
txt_price:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_price:setFontSize(45)
txt_price:setString([[6元]])
txt_price:setLayoutComponentEnabled(true)
txt_price:setName("txt_price")
txt_price:setTag(103)
txt_price:setCascadeColorEnabled(true)
txt_price:setCascadeOpacityEnabled(true)
txt_price:setPosition(0.0000, 225.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_price)
layout:setSize({width = 79.0000, height = 55.0000})
layout:setLeftMargin(-39.5000)
layout:setRightMargin(-39.5000)
layout:setTopMargin(-252.5000)
layout:setBottomMargin(197.5000)
node_store_item:addChild(txt_price)

--Create txt_gold
local txt_gold = ccui.Text:create()
txt_gold:ignoreContentAdaptWithSize(true)
txt_gold:setTextAreaSize({width = 0, height = 0})
txt_gold:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_gold:setFontSize(45)
txt_gold:setString([[68,000金币]])
txt_gold:setLayoutComponentEnabled(true)
txt_gold:setName("txt_gold")
txt_gold:setTag(104)
txt_gold:setCascadeColorEnabled(true)
txt_gold:setCascadeOpacityEnabled(true)
txt_gold:setPosition(0.0000, -170.0000)
txt_gold:setTextColor({r = 228, g = 96, b = 23})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_gold)
layout:setSize({width = 266.0000, height = 55.0000})
layout:setLeftMargin(-133.0000)
layout:setRightMargin(-133.0000)
layout:setTopMargin(142.5000)
layout:setBottomMargin(-197.5000)
node_store_item:addChild(txt_gold)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = node_store_item
return result;
end

return Result

