--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create hall_bottom_node
local hall_bottom_node=cc.Node:create()
hall_bottom_node:setName("hall_bottom_node")

--Create img_hall_bottom_bg
local img_hall_bottom_bg = ccui.ImageView:create()
img_hall_bottom_bg:ignoreContentAdaptWithSize(false)
img_hall_bottom_bg:loadTexture("assets/hall/hall_bottom_bg.png",0)
img_hall_bottom_bg:setLayoutComponentEnabled(true)
img_hall_bottom_bg:setName("img_hall_bottom_bg")
img_hall_bottom_bg:setTag(9)
img_hall_bottom_bg:setCascadeColorEnabled(true)
img_hall_bottom_bg:setCascadeOpacityEnabled(true)
img_hall_bottom_bg:setPosition(0.0000, 105.1641)
layout = ccui.LayoutComponent:bindLayoutComponent(img_hall_bottom_bg)
layout:setSize({width = 1920.0000, height = 122.0000})
layout:setLeftMargin(-960.0000)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-166.1641)
layout:setBottomMargin(44.1641)
hall_bottom_node:addChild(img_hall_bottom_bg)

--Create img_activity
local img_activity = ccui.ImageView:create()
img_activity:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_activity:loadTexture("hall_activity.png",1)
img_activity:setLayoutComponentEnabled(true)
img_activity:setName("img_activity")
img_activity:setTag(12)
img_activity:setCascadeColorEnabled(true)
img_activity:setCascadeOpacityEnabled(true)
img_activity:setPosition(-197.9561, 136.4223)
layout = ccui.LayoutComponent:bindLayoutComponent(img_activity)
layout:setSize({width = 180.0000, height = 180.0000})
layout:setLeftMargin(-287.9561)
layout:setRightMargin(107.9561)
layout:setTopMargin(-226.4223)
layout:setBottomMargin(46.4223)
hall_bottom_node:addChild(img_activity)

--Create img_task
local img_task = ccui.ImageView:create()
img_task:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_task:loadTexture("hall_task.png",1)
img_task:setLayoutComponentEnabled(true)
img_task:setName("img_task")
img_task:setTag(41)
img_task:setCascadeColorEnabled(true)
img_task:setCascadeOpacityEnabled(true)
img_task:setPosition(-431.9722, 136.2568)
layout = ccui.LayoutComponent:bindLayoutComponent(img_task)
layout:setSize({width = 180.0000, height = 180.0000})
layout:setLeftMargin(-521.9722)
layout:setRightMargin(341.9722)
layout:setTopMargin(-226.2568)
layout:setBottomMargin(46.2568)
hall_bottom_node:addChild(img_task)

--Create img_rank
local img_rank = ccui.ImageView:create()
img_rank:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_rank:loadTexture("hall_rank.png",1)
img_rank:setLayoutComponentEnabled(true)
img_rank:setName("img_rank")
img_rank:setTag(11)
img_rank:setCascadeColorEnabled(true)
img_rank:setCascadeOpacityEnabled(true)
img_rank:setPosition(3.2025, 136.4223)
layout = ccui.LayoutComponent:bindLayoutComponent(img_rank)
layout:setSize({width = 180.0000, height = 180.0000})
layout:setLeftMargin(-86.7975)
layout:setRightMargin(-93.2025)
layout:setTopMargin(-226.4223)
layout:setBottomMargin(46.4223)
hall_bottom_node:addChild(img_rank)

--Create img_shop
local img_shop = ccui.ImageView:create()
img_shop:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_shop:loadTexture("hall_shop.png",1)
img_shop:setLayoutComponentEnabled(true)
img_shop:setName("img_shop")
img_shop:setTag(10)
img_shop:setCascadeColorEnabled(true)
img_shop:setCascadeOpacityEnabled(true)
img_shop:setPosition(217.7396, 136.4223)
layout = ccui.LayoutComponent:bindLayoutComponent(img_shop)
layout:setSize({width = 180.0000, height = 180.0000})
layout:setLeftMargin(127.7396)
layout:setRightMargin(-307.7396)
layout:setTopMargin(-226.4223)
layout:setBottomMargin(46.4223)
hall_bottom_node:addChild(img_shop)

--Create img_first_charge
local img_first_charge = ccui.ImageView:create()
img_first_charge:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_first_charge:loadTexture("hall_firstcharge.png",1)
img_first_charge:setLayoutComponentEnabled(true)
img_first_charge:setName("img_first_charge")
img_first_charge:setTag(67)
img_first_charge:setCascadeColorEnabled(true)
img_first_charge:setCascadeOpacityEnabled(true)
img_first_charge:setPosition(454.9998, 141.0845)
layout = ccui.LayoutComponent:bindLayoutComponent(img_first_charge)
layout:setSize({width = 190.0000, height = 140.0000})
layout:setLeftMargin(359.9998)
layout:setRightMargin(-549.9998)
layout:setTopMargin(-211.0845)
layout:setBottomMargin(71.0845)
hall_bottom_node:addChild(img_first_charge)

--Create img_first_charge1
local img_first_charge1 = ccui.ImageView:create()
img_first_charge1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_bottom.plist")
img_first_charge1:loadTexture("hall_firstcharge1.png",1)
img_first_charge1:setLayoutComponentEnabled(true)
img_first_charge1:setName("img_first_charge1")
img_first_charge1:setTag(68)
img_first_charge1:setCascadeColorEnabled(true)
img_first_charge1:setCascadeOpacityEnabled(true)
img_first_charge1:setPosition(453.0038, 86.1010)
layout = ccui.LayoutComponent:bindLayoutComponent(img_first_charge1)
layout:setSize({width = 140.0000, height = 90.0000})
layout:setLeftMargin(383.0038)
layout:setRightMargin(-523.0038)
layout:setTopMargin(-131.1010)
layout:setBottomMargin(41.1010)
hall_bottom_node:addChild(img_first_charge1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = hall_bottom_node
return result;
end

return Result

