--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create input_popup_layer
local input_popup_layer=cc.Node:create()
input_popup_layer:setName("input_popup_layer")
layout = ccui.LayoutComponent:bindLayoutComponent(input_popup_layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("assets/common/popup_bg1.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(102)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(960.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4167)
layout:setPercentHeight(0.4630)
layout:setSize({width = 800.0000, height = 500.0000})
layout:setLeftMargin(560.0000)
layout:setRightMargin(560.0000)
layout:setTopMargin(290.0000)
layout:setBottomMargin(290.0000)
input_popup_layer:addChild(img_bg)

--Create img_title_bg
local img_title_bg = ccui.ImageView:create()
img_title_bg:ignoreContentAdaptWithSize(false)
img_title_bg:loadTexture("assets/common/title_bg1.png",0)
img_title_bg:setScale9Enabled(true)
img_title_bg:setCapInsets({x = 21, y = 21, width = 758, height = 79})
img_title_bg:setLayoutComponentEnabled(true)
img_title_bg:setName("img_title_bg")
img_title_bg:setTag(110)
img_title_bg:setCascadeColorEnabled(true)
img_title_bg:setCascadeOpacityEnabled(true)
img_title_bg:setPosition(400.0000, 460.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_title_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9200)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1740)
layout:setSize({width = 800.0000, height = 87.0000})
layout:setTopMargin(-3.5000)
layout:setBottomMargin(416.5000)
img_bg:addChild(img_title_bg)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_title:setFontSize(50)
txt_title:setString([[麻将乐趣]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(112)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setPosition(400.0000, 460.5500)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9211)
layout:setPercentWidth(0.2513)
layout:setPercentHeight(0.1220)
layout:setSize({width = 201.0000, height = 61.0000})
layout:setLeftMargin(299.5000)
layout:setRightMargin(299.5000)
layout:setTopMargin(8.9500)
layout:setBottomMargin(430.0500)
img_bg:addChild(txt_title)

--Create img_input_bg
local img_input_bg = ccui.ImageView:create()
img_input_bg:ignoreContentAdaptWithSize(false)
img_input_bg:loadTexture("assets/common/input_bg.png",0)
img_input_bg:setScale9Enabled(true)
img_input_bg:setCapInsets({x = 21, y = 21, width = 30, height = 44})
img_input_bg:setLayoutComponentEnabled(true)
img_input_bg:setName("img_input_bg")
img_input_bg:setTag(59)
img_input_bg:setCascadeColorEnabled(true)
img_input_bg:setCascadeOpacityEnabled(true)
img_input_bg:setPosition(400.0000, 265.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_input_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5300)
layout:setPercentWidth(0.8875)
layout:setPercentHeight(0.1720)
layout:setSize({width = 710.0000, height = 86.0000})
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(192.0000)
layout:setBottomMargin(222.0000)
img_bg:addChild(img_input_bg)

--Create txt_input_tip
local txt_input_tip = ccui.Text:create()
txt_input_tip:ignoreContentAdaptWithSize(true)
txt_input_tip:setTextAreaSize({width = 0, height = 0})
txt_input_tip:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_input_tip:setFontSize(30)
txt_input_tip:setString([[提示：剩余修改次数1次，成为VIP后可获得更多
修改次]])
txt_input_tip:setLayoutComponentEnabled(true)
txt_input_tip:setName("txt_input_tip")
txt_input_tip:setTag(73)
txt_input_tip:setCascadeColorEnabled(true)
txt_input_tip:setCascadeOpacityEnabled(true)
txt_input_tip:setAnchorPoint(0.0000, 0.5000)
txt_input_tip:setPosition(69.0400, 167.9000)
txt_input_tip:setTextColor({r = 244, g = 164, b = 96})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_input_tip)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0863)
layout:setPositionPercentY(0.3358)
layout:setPercentWidth(0.8075)
layout:setPercentHeight(0.1480)
layout:setSize({width = 646.0000, height = 74.0000})
layout:setLeftMargin(69.0400)
layout:setRightMargin(84.9600)
layout:setTopMargin(295.1000)
layout:setBottomMargin(130.9000)
img_bg:addChild(txt_input_tip)

--Create img_yes
local img_yes = ccui.ImageView:create()
img_yes:ignoreContentAdaptWithSize(false)
img_yes:loadTexture("assets/common/btn_yellow1.png",0)
img_yes:setScale9Enabled(true)
img_yes:setCapInsets({x = 21, y = 21, width = 216, height = 58})
img_yes:setLayoutComponentEnabled(true)
img_yes:setName("img_yes")
img_yes:setTag(116)
img_yes:setCascadeColorEnabled(true)
img_yes:setCascadeOpacityEnabled(true)
img_yes:setPosition(400.0000, 61.6500)
layout = ccui.LayoutComponent:bindLayoutComponent(img_yes)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1233)
layout:setPercentWidth(0.2063)
layout:setPercentHeight(0.1400)
layout:setSize({width = 165.0000, height = 70.0000})
layout:setLeftMargin(317.5000)
layout:setRightMargin(317.5000)
layout:setTopMargin(403.3500)
layout:setBottomMargin(26.6500)
img_bg:addChild(img_yes)

--Create txt_yes
local txt_yes = ccui.Text:create()
txt_yes:ignoreContentAdaptWithSize(true)
txt_yes:setTextAreaSize({width = 0, height = 0})
txt_yes:setFontName("assets/font/FZZhengHeiS-B-GB.ttf")
txt_yes:setFontSize(40)
txt_yes:setString([[确定]])
txt_yes:setLayoutComponentEnabled(true)
txt_yes:setName("txt_yes")
txt_yes:setTag(117)
txt_yes:setCascadeColorEnabled(true)
txt_yes:setCascadeOpacityEnabled(true)
txt_yes:setPosition(82.5000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_yes)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4970)
layout:setPercentHeight(0.7000)
layout:setSize({width = 82.0000, height = 49.0000})
layout:setLeftMargin(41.5000)
layout:setRightMargin(41.5000)
layout:setTopMargin(10.5000)
layout:setBottomMargin(10.5000)
img_yes:addChild(txt_yes)

--Create img_close
local img_close = ccui.ImageView:create()
img_close:ignoreContentAdaptWithSize(false)
img_close:loadTexture("assets/common/pop_close1.png",0)
img_close:setLayoutComponentEnabled(true)
img_close:setName("img_close")
img_close:setTag(66)
img_close:setCascadeColorEnabled(true)
img_close:setCascadeOpacityEnabled(true)
img_close:setPosition(796.9717, 493.3353)
layout = ccui.LayoutComponent:bindLayoutComponent(img_close)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9962)
layout:setPositionPercentY(0.9867)
layout:setPercentWidth(0.1200)
layout:setPercentHeight(0.1940)
layout:setSize({width = 96.0000, height = 97.0000})
layout:setLeftMargin(748.9717)
layout:setRightMargin(-44.9717)
layout:setTopMargin(-41.8353)
layout:setBottomMargin(444.8353)
img_bg:addChild(img_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = input_popup_layer
return result;
end

return Result

