--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create hall_top_node
local hall_top_node=cc.Node:create()
hall_top_node:setName("hall_top_node")

--Create node_head
local node_head=cc.Node:create()
node_head:setName("node_head")
node_head:setTag(89)
node_head:setCascadeColorEnabled(true)
node_head:setCascadeOpacityEnabled(true)
node_head:setPosition(-800.0000, -100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head)
layout:setLeftMargin(-800.0000)
layout:setRightMargin(800.0000)
layout:setTopMargin(100.0000)
layout:setBottomMargin(-100.0000)
hall_top_node:addChild(node_head)

--Create img_top_title_bg
local img_top_title_bg = ccui.ImageView:create()
img_top_title_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_top_title_bg:loadTexture("hall_title_bg.png",1)
img_top_title_bg:setLayoutComponentEnabled(true)
img_top_title_bg:setName("img_top_title_bg")
img_top_title_bg:setTag(14)
img_top_title_bg:setCascadeColorEnabled(true)
img_top_title_bg:setCascadeOpacityEnabled(true)
img_top_title_bg:setPosition(7.5118, -78.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_title_bg)
layout:setSize({width = 584.0000, height = 136.0000})
layout:setLeftMargin(-284.4882)
layout:setRightMargin(-299.5118)
layout:setTopMargin(10.8800)
layout:setBottomMargin(-146.8800)
hall_top_node:addChild(img_top_title_bg)

--Create img_top_title
local img_top_title = ccui.ImageView:create()
img_top_title:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_top_title:loadTexture("hall_title_name.png",1)
img_top_title:setLayoutComponentEnabled(true)
img_top_title:setName("img_top_title")
img_top_title:setTag(15)
img_top_title:setCascadeColorEnabled(true)
img_top_title:setCascadeOpacityEnabled(true)
img_top_title:setPosition(7.5118, -78.8760)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top_title)
layout:setSize({width = 336.0000, height = 100.0000})
layout:setLeftMargin(-160.4882)
layout:setRightMargin(-175.5118)
layout:setTopMargin(28.8760)
layout:setBottomMargin(-128.8760)
hall_top_node:addChild(img_top_title)

--Create img_flower
local img_flower = ccui.ImageView:create()
img_flower:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_flower:loadTexture("hall_flower.png",1)
img_flower:setLayoutComponentEnabled(true)
img_flower:setName("img_flower")
img_flower:setTag(60)
img_flower:setCascadeColorEnabled(true)
img_flower:setCascadeOpacityEnabled(true)
img_flower:setPosition(770.2825, -127.7799)
layout = ccui.LayoutComponent:bindLayoutComponent(img_flower)
layout:setSize({width = 433.0000, height = 166.0000})
layout:setLeftMargin(553.7825)
layout:setRightMargin(-986.7825)
layout:setTopMargin(44.7799)
layout:setBottomMargin(-210.7799)
hall_top_node:addChild(img_flower)

--Create img_msg
local img_msg = ccui.ImageView:create()
img_msg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_msg:loadTexture("hall_msg.png",1)
img_msg:setLayoutComponentEnabled(true)
img_msg:setName("img_msg")
img_msg:setTag(17)
img_msg:setCascadeColorEnabled(true)
img_msg:setCascadeOpacityEnabled(true)
img_msg:setPosition(368.2838, -78.7250)
layout = ccui.LayoutComponent:bindLayoutComponent(img_msg)
layout:setSize({width = 103.0000, height = 95.0000})
layout:setLeftMargin(316.7838)
layout:setRightMargin(-419.7838)
layout:setTopMargin(31.2250)
layout:setBottomMargin(-126.2250)
hall_top_node:addChild(img_msg)

--Create img_setting
local img_setting = ccui.ImageView:create()
img_setting:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_setting:loadTexture("hall_set.png",1)
img_setting:setLayoutComponentEnabled(true)
img_setting:setName("img_setting")
img_setting:setTag(16)
img_setting:setCascadeColorEnabled(true)
img_setting:setCascadeOpacityEnabled(true)
img_setting:setPosition(546.0997, -88.4878)
layout = ccui.LayoutComponent:bindLayoutComponent(img_setting)
layout:setSize({width = 103.0000, height = 95.0000})
layout:setLeftMargin(494.5997)
layout:setRightMargin(-597.5997)
layout:setTopMargin(40.9878)
layout:setBottomMargin(-135.9878)
hall_top_node:addChild(img_setting)

--Create img_friend
local img_friend = ccui.ImageView:create()
img_friend:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_friend:loadTexture("hall_friend.png",1)
img_friend:setLayoutComponentEnabled(true)
img_friend:setName("img_friend")
img_friend:setTag(58)
img_friend:setCascadeColorEnabled(true)
img_friend:setCascadeOpacityEnabled(true)
img_friend:setPosition(864.2721, -81.7800)
layout = ccui.LayoutComponent:bindLayoutComponent(img_friend)
layout:setSize({width = 171.0000, height = 186.0000})
layout:setLeftMargin(778.7721)
layout:setRightMargin(-949.7721)
layout:setTopMargin(-11.2200)
layout:setBottomMargin(-174.7800)
hall_top_node:addChild(img_friend)

--Create img_pendant
local img_pendant = ccui.ImageView:create()
img_pendant:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_pendant:loadTexture("hall_pendant.png",1)
img_pendant:setLayoutComponentEnabled(true)
img_pendant:setName("img_pendant")
img_pendant:setTag(59)
img_pendant:setCascadeColorEnabled(true)
img_pendant:setCascadeOpacityEnabled(true)
img_pendant:setPosition(865.2743, -215.7800)
layout = ccui.LayoutComponent:bindLayoutComponent(img_pendant)
layout:setSize({width = 68.0000, height = 154.0000})
layout:setLeftMargin(831.2743)
layout:setRightMargin(-899.2743)
layout:setTopMargin(138.7800)
layout:setBottomMargin(-292.7800)
hall_top_node:addChild(img_pendant)

--Create img_notice_bg
local img_notice_bg = ccui.ImageView:create()
img_notice_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_notice_bg:loadTexture("hall_notice_bg.png",1)
img_notice_bg:setLayoutComponentEnabled(true)
img_notice_bg:setName("img_notice_bg")
img_notice_bg:setTag(91)
img_notice_bg:setCascadeColorEnabled(true)
img_notice_bg:setCascadeOpacityEnabled(true)
img_notice_bg:setPosition(0.0000, -193.9700)
layout = ccui.LayoutComponent:bindLayoutComponent(img_notice_bg)
layout:setSize({width = 1207.0000, height = 50.0000})
layout:setLeftMargin(-603.5000)
layout:setRightMargin(-603.5000)
layout:setTopMargin(168.9700)
layout:setBottomMargin(-218.9700)
hall_top_node:addChild(img_notice_bg)

--Create img_notice
local img_notice = ccui.ImageView:create()
img_notice:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("assets/hall/plist/hall_top.plist")
img_notice:loadTexture("hall_notice_horn.png",1)
img_notice:setLayoutComponentEnabled(true)
img_notice:setName("img_notice")
img_notice:setTag(92)
img_notice:setCascadeColorEnabled(true)
img_notice:setCascadeOpacityEnabled(true)
img_notice:setPosition(-535.6768, -191.0217)
layout = ccui.LayoutComponent:bindLayoutComponent(img_notice)
layout:setSize({width = 108.0000, height = 76.0000})
layout:setLeftMargin(-589.6768)
layout:setRightMargin(481.6768)
layout:setTopMargin(153.0217)
layout:setBottomMargin(-229.0217)
hall_top_node:addChild(img_notice)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = hall_top_node
return result;
end

return Result

